{{- if .Values.keycloak.defaultConfig }}
---
apiVersion: "external-secrets.io/v1"
kind: ExternalSecret
metadata:
  name: acs-oidc-client-secret
  namespace: {{ .Release.Namespace }}
  {{- if .Values.externalSecrets.acs.metadata }}
  {{- toYaml .Values.externalSecrets.acs.metadata | nindent 2 }}
  {{- end }}
spec:
  {{ include "keycloak.externalSecrets.lifecycle" (dict "local" .Values.externalSecrets.acs "global" .Values.global) | nindent 2 }}
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: acs-oidc-client-secret
    {{ include "keycloak.externalSecrets.targetLifecycle" (dict "local" .Values.externalSecrets.acs "global" .Values.global) | nindent 4 }}
    template:
      {{- if .Values.externalSecrets.acs.targetMetadata }}
      metadata:
        {{- toYaml .Values.externalSecrets.acs.targetMetadata | nindent 8 }}
      {{- end }}
      type: Opaque
      data:
        client-secret: "{{ `{{ .client_secret }}` }}"
  data:
  - secretKey: client_secret
    remoteRef:
      key: {{ .Values.keycloak.oidcSecrets.acsClient.vaultPath }}
      property: admin-password
{{- end }}
