{{- range .Values.keycloak.extraSecrets }}
---
apiVersion: "external-secrets.io/v1"
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  {{- with .metadata }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
spec:
  {{ include "keycloak.extraSecrets.lifecycle" (dict "local" . "global" $.Values.global) | nindent 2 }}
  secretStoreRef:
    name: {{ $.Values.global.secretStore.name }}
    kind: {{ $.Values.global.secretStore.kind }}
  target:
    name: {{ .targetName | default .name }}
    {{ include "keycloak.extraSecrets.targetLifecycle" (dict "local" . "global" $.Values.global) | nindent 4 }}
    template:
      {{- with .targetMetadata }}
      metadata:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      type: Opaque
      data:
        {{- range $key, $val := .templateData }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
  data:
  {{- range .data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRef.key }}
      property: {{ .remoteRef.property }}
  {{- end }}
{{- end }}
