{{- if eq .Values.keycloak.adminUser.enabled true }}
apiVersion: "external-secrets.io/v1"
kind: ExternalSecret
metadata:
  name: keycloak-admin-user
  namespace: {{ .Release.Namespace }}
  {{- if .Values.externalSecrets.adminUser.metadata }}
  {{- toYaml .Values.externalSecrets.adminUser.metadata | nindent 2 }}
  {{- end }}
spec:
  {{ include "keycloak.externalSecrets.lifecycle" (dict "local" .Values.externalSecrets.adminUser "global" .Values.global) | nindent 2 }}
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: {{ .Values.keycloak.adminUser.secretName }}
    {{ include "keycloak.externalSecrets.targetLifecycle" (dict "local" .Values.externalSecrets.adminUser "global" .Values.global) | nindent 4 }}
    template:
      {{- if .Values.externalSecrets.adminUser.targetMetadata }}
      metadata:
        {{- toYaml .Values.externalSecrets.adminUser.targetMetadata | nindent 8 }}
      {{- end }}
      type: Opaque
      data:
        username: "{{ .Values.keycloak.adminUser.username }}"
        password: "{{ `{{ .admin_password }}` }}"
  data:
  - secretKey: admin_password
    remoteRef:
      key: {{ .Values.keycloak.adminUser.passwordVaultKey }}
      property: admin-password
{{- end }}
