{{- if and .Values.keycloak.defaultConfig (default false .Values.keycloak.oidcSecrets.qtodo.enabled) }}
apiVersion: "external-secrets.io/v1"
kind: ExternalSecret
metadata:
  name: oidc-client-secret
  namespace: {{ .Release.Namespace }}
  {{- if .Values.externalSecrets.oidcClientSecret.metadata }}
  {{- toYaml .Values.externalSecrets.oidcClientSecret.metadata | nindent 2 }}
  {{- end }}
spec:
  {{ include "keycloak.externalSecrets.lifecycle" (dict "local" .Values.externalSecrets.oidcClientSecret "global" .Values.global) | nindent 2 }}
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: oidc-client-secret
    {{ include "keycloak.externalSecrets.targetLifecycle" (dict "local" .Values.externalSecrets.oidcClientSecret "global" .Values.global) | nindent 4 }}
    template:
      {{- if .Values.externalSecrets.oidcClientSecret.targetMetadata }}
      metadata:
        {{- toYaml .Values.externalSecrets.oidcClientSecret.targetMetadata | nindent 8 }}
      {{- end }}
      type: Opaque
      data:
        client-secret: "{{ `{{ .client_secret }}` }}"
  data:
  - secretKey: client_secret
    remoteRef:
      key: {{ .Values.keycloak.oidcSecrets.qtodo.vaultPath }}
      property: client-secret
{{- end }}
